import { useEffect, useState } from 'react';
import { ShieldCheck, LogOut, RefreshCw, Ticket, Activity, LockKeyhole } from 'lucide-react';

interface TicketRow { id: string; email: string; subject: string; message: string; status: string; createdAt: string; }
export function AdminDashboard() {
  const [loggedIn, setLoggedIn] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [tickets, setTickets] = useState<TicketRow[]>([]); const [loading, setLoading] = useState(false);
  const load = async () => { setLoading(true); const response = await fetch('/api/admin/tickets'); if (response.ok) { setLoggedIn(true); setTickets(await response.json()); } else setLoggedIn(false); setLoading(false); };
  useEffect(() => { load(); }, []);
  const login = async (event: React.FormEvent) => { event.preventDefault(); setError(''); const response = await fetch('/api/admin/login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password }) }); if (!response.ok) { setError('Invalid administrator credentials.'); return; } setPassword(''); await load(); };
  const logout = async () => { await fetch('/api/admin/logout', { method: 'POST' }); setLoggedIn(false); };
  const update = async (id: string, status: string) => { await fetch(`/api/admin/tickets/${id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status }) }); load(); };
  if (!loggedIn) return <main className="min-h-screen flex items-center justify-center px-4 bg-bg"><form onSubmit={login} className="w-full max-w-md bg-card border border-border-main rounded-3xl p-7 shadow-2xl space-y-5"><div className="flex items-center gap-3"><div className="p-3 rounded-2xl bg-[#00A3FF]/10 text-[#00A3FF]"><LockKeyhole /></div><div><h1 className="text-2xl font-extrabold">Admin control panel</h1><p className="text-sm text-text-secondary">Protected operations and support management</p></div></div><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Admin email" className="w-full bg-input rounded-xl px-4 py-3" /><input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Admin password" className="w-full bg-input rounded-xl px-4 py-3" />{error && <p className="text-sm text-red-500">{error}</p>}<button className="w-full bg-[#00A3FF] text-white rounded-xl py-3 font-bold">Sign in securely</button><p className="text-xs text-text-secondary">Admin credentials are checked on the server. Nothing is stored in the browser.</p></form></main>;
  return <main className="min-h-screen bg-bg px-4 py-8"><div className="max-w-6xl mx-auto space-y-6"><header className="flex flex-wrap gap-4 items-center justify-between"><div><div className="flex items-center gap-2 text-[#00A3FF]"><ShieldCheck className="w-5 h-5" /><span className="text-xs font-bold uppercase tracking-widest">Protected workspace</span></div><h1 className="text-3xl font-extrabold mt-2">Operations control panel</h1><p className="text-text-secondary">Monitor support and application health without exposing privileged controls publicly.</p></div><div className="flex gap-2"><button onClick={load} className="p-3 rounded-xl border border-border-main bg-card"><RefreshCw className={loading ? 'animate-spin' : ''} /></button><button onClick={logout} className="px-4 py-3 rounded-xl border border-border-main bg-card flex gap-2 items-center"><LogOut className="w-4 h-4" /> Sign out</button></div></header><section className="grid md:grid-cols-3 gap-4"><div className="bg-card border border-border-main rounded-2xl p-5"><Ticket className="text-[#00A3FF]" /><p className="text-sm text-text-secondary mt-4">Total tickets</p><p className="text-3xl font-extrabold">{tickets.length}</p></div><div className="bg-card border border-border-main rounded-2xl p-5"><Activity className="text-emerald-500" /><p className="text-sm text-text-secondary mt-4">System status</p><p className="text-xl font-extrabold text-emerald-500">Operational</p></div><div className="bg-card border border-border-main rounded-2xl p-5"><ShieldCheck className="text-violet-500" /><p className="text-sm text-text-secondary mt-4">Access</p><p className="text-xl font-extrabold">Server protected</p></div></section><section className="bg-card border border-border-main rounded-2xl overflow-hidden"><div className="p-5 border-b border-border-main"><h2 className="font-extrabold text-lg">Support tickets</h2></div><div className="divide-y divide-border-main">{tickets.length === 0 ? <p className="p-8 text-center text-text-secondary">No support tickets yet.</p> : tickets.map((item) => <article key={item.id} className="p-5 flex flex-col lg:flex-row gap-4 justify-between"><div><div className="flex flex-wrap gap-2 items-center"><h3 className="font-bold">{item.subject}</h3><span className="text-xs px-2 py-1 rounded-full bg-input">{item.status}</span></div><p className="text-sm text-text-secondary mt-1">{item.email} · {new Date(item.createdAt).toLocaleString()}</p><p className="mt-3 text-sm whitespace-pre-wrap">{item.message}</p></div><select value={item.status} onChange={(e) => update(item.id, e.target.value)} className="h-10 bg-input rounded-xl px-3"><option>open</option><option>in_progress</option><option>resolved</option></select></article>)}</div></section></div></main>;
}
